# Analiza reprezentanc na nogometnem svetovnem prvenstvu 2026
Analizirala bom podatke o reprezentancah na nogometnem svetovnem prvenstvu 2026, ki so objavljeni na spletni strani [StatBunker](https://www.statbunker.com/competitions/Sections?comp_id=790&section_id=1667).
Uporabila bom podatke o [zadetih golih](https://www.statbunker.com/competitions/GoalsFor?comp_id=790), [prejetih golih](https://www.statbunker.com/competitions/GoalsAgainst?comp_id=790), [uspešnosti vratarjev](https://www.statbunker.com/competitions/Top10KeepersCleanSheets?comp_id=790) in [načinih doseganja golov](https://www.statbunker.com/competitions/TeamsGoalScorersTypeOfPlay?comp_id=790). 
Spodaj so podatki predstavljeni s tabelami. Kratice v prvih vrsticah imajo naslednje pomene: **FH** - prvi polčas, **SH** - drugi polčas, **F15** - prvih 15 minut, **L10** - zadnjih 10 minut, **Pld** - število odigranih tekem in **CS** - število tekem brez prejetega gola.

In [ ]:
import pandas as pd

goals_for = pd.read_csv("podatki/goals_for.csv")
goals_against = pd.read_csv("podatki/goals_against.csv")
clean_sheets = pd.read_csv("podatki/clean_sheets.csv")
goal_types = pd.read_csv("podatki/goal_types.csv")

## Zadeti goli

In [23]:
goals_for = goals_for.replace("-", 0)
goals_for

    Goals For                   Clubs FH  SH F15 L10  Pld
0          20                 England  9  11   2   5    8
1          20                  France  5  15   2   4    8
2          19               Argentina  6  13   1  10    8
3          14                   Spain  7   7   1   4    8
4          14                 Belgium  4  10   1   6    6
5          13                  Norway  6   7   0   3    6
6          11                 Germany  4   7   2   2    4
7          11             Netherlands  4   7   3   1    4
8          11           United States  8   3   3   2    5
9          10                 Senegal  2   8   1   3    4
10         10                  Brazil  6   4   1   2    5
11         10                  Mexico  4   6   1   1    5
12         10             Switzerland  2   8   1   3    6
13         10                 Morocco  4   6   1   4    6
14          9                  Canada  3   6   0   2    5
15          8                   Japan  3   5   1   2    4
16          8                Portugal  4   4   2   2    5
17          8                   Egypt  4   4   3   1    5
18          7                  Sweden  2   5   1   2    4
19          6                 Austria  2   4   0   2    4
20          6                 Croatia  3   3   0   1    4
21          5        DR Congo (Zaire)  2   3   1   1    4
22          5                 Algeria  1   4   0   2    4
23          5                Colombia  2   3   1   1    5
24          5             Ivory Coast  2   3   1   1    4
25          5  Bosnia and Herzegovina  3   2   0   2    4
26          4              Cape Verde  1   3   0   1    4
27          4             New Zealand  2   2   2   1    3
28          3               Australia  1   2   0   0    4
29          3                  Turkey  2   1   1   1    3
30          3                 Uruguay  2   1   0   1    3
31          3                  Jordan  1   2   0   0    3
32          3                    Iran  2   1   1   0    3
33          3                Paraguay  2   1   1   0    5
34          2                   Ghana  0   2   0   1    4
35          2                 Tunisia  1   1   0   0    3
36          2                   Qatar  1   1   0   1    3
37          2                 Ecuador  1   1   1   0    4
38          2          Czech Republic  1   1   1   0    3
39          2            South Africa  0   2   0   1    4
40          2              Uzbekistan  1   1   1   0    3
41          2             South Korea  0   2   0   1    3
42          2                   Haiti  2   0   1   0    3
43          1                 Curacao  1   0   0   0    3
44          1                    Iraq  1   0   0   0    3
45          1                Scotland  1   0   0   0    3
46          1            Saudi Arabia  1   0   0   0    3
47          0                  Panama  0   0   0   0    3

## Prejeti goli

In [25]:
goals_against = goals_against.replace("-", 0)
goals_against

    Goals Against                   Clubs FH SH F15 L10  Pld
0               1                   Spain  1  0   0   0    8
1               1                Colombia  0  1   0   0    5
2               3                    Iran  2  1   2   0    3
3               3                   Ghana  2  1   1   1    4
4               3                Portugal  1  2   0   1    5
5               3                  Mexico  2  1   0   0    5
6               3             South Korea  0  3   0   0    3
7               3               Australia  3  0   2   0    4
8               4                 Uruguay  3  1   0   0    3
9               4            South Africa  2  2   2   1    4
10              4                 Ecuador  3  1   1   1    4
11              4             Ivory Coast  1  3   0   2    4
12              4                  Panama  0  4   0   1    3
13              4                  Brazil  2  2   0   1    5
14              4                Scotland  3  1   2   0    3
15              5             Netherlands  0  5   0   2    4
16              5              Cape Verde  3  2   0   2    4
17              5        DR Congo (Zaire)  2  3   2   1    4
18              5            Saudi Arabia  3  2   1   1    3
19              5                   Japan  0  5   0   1    4
20              5                 Germany  4  1   1   0    4
21              5                  Turkey  3  2   2   0    3
22              6                Paraguay  3  3   1   1    5
23              6             Switzerland  1  5   1   4    6
24              6          Czech Republic  0  6   0   3    3
25              6                  Canada  1  5   0   2    5
26              6                 Morocco  3  3   1   0    6
27              7                   Egypt  2  5   2   2    5
28              7                 Belgium  4  3   0   2    6
29              7                 Croatia  2  5   1   2    4
30              8                   Haiti  6  2   0   1    3
31              8                  Jordan  3  5   0   3    3
32              8  Bosnia and Herzegovina  2  6   0   4    4
33              8               Argentina  1  7   1   2    8
34              8           United States  4  4   2   2    5
35              9                 Austria  3  6   0   3    4
36              9                 Curacao  4  5   2   1    3
37              9                 Senegal  1  8   0   5    4
38              9                 Algeria  4  5   1   1    4
39             10             New Zealand  2  8   0   3    3
40             10                   Qatar  6  4   0   2    3
41             10                  Sweden  4  6   1   1    4
42             10                  France  6  4   1   3    8
43             11              Uzbekistan  4  7   1   3    3
44             11                  Norway  5  6   1   4    6
45             12                 England  5  7   1   3    8
46             12                    Iraq  4  8   2   2    3
47             12                 Tunisia  6  6   4   3    3

## Uspešnost vratarjev

In [26]:
clean_sheets

,Players,Clubs,Nationality,CS,Pld,%
0,Unai Simon,Spain,Spain,7,8,87.50%
1,Raul Rangel,Mexico,Mexico,4,5,80.00%
2,Camilo Vargas,Colombia,Colombia,4,5,80.00%
3,Mike Maignan,France,France,4,8,50.00%
4,Josimar Vozinha,Cape Verde,Cape Verde,2,4,50.00%
5,Patrick Beach,Australia,Australia,2,4,50.00%
6,Matt Freese,United States,United States,2,4,50.00%
7,Yahia Fofana,Ivory Coast,France,2,4,50.00%
8,Alisson,Brazil,Brazil,2,5,40.00%
9,Orlando Gill,Paraguay,Paraguay,2,5,40.00%
10,Maxime Crepeau,Canada,Canada,2,5,40.00%
11,Diogo Costa,Portugal,Portugal,2,5,40.00%
12,Yassine Bounou,Morocco,Morocco,2,6,33.33%
13,Gregor Kobel,Switzerland,Switzerland,2,6,33.33%
14,Jordan Pickford,England,England,2,7,28.57%
15,Emiliano Martinez,Argentina,Argentina,2,8,25.00%
16,Benjamin Asare,Ghana,Ghana,1,2,50.00%
17,Lawrence Ati-Zigi,Ghana,Ghana,1,2,50.00%
18,Mory Diaw,Senegal,Senegal,1,2,50.00%
19,Eloy Room,Curacao,Curacao,1,3,33.33%
20,Angus Gunn,Scotland,Scotland,1,3,33.33%
21,Mohammed Al-Owais,Saudi Arabia,Saudi Arabia,1,3,33.33%
22,Alireza Beiranvand,Iran,Iran,1,3,33.33%
23,Zion Suzuki,Japan,Japan,1,4,25.00%
24,Dominik Livakovic,Croatia,Croatia,1,4,25.00%
25,Ronwen Williams,South Africa,South Africa,1,4,25.00%
26,Hernan Galindez,Ecuador,Ecuador,1,4,25.00%
27,Thibaut Courtois,Belgium,Belgium,1,6,16.67%
28,Oussama Benbot,Algeria,Algeria,0,1,0.00%
29,Dean Henderson,England,England,0,1,0.00%
30,Moulib Chamakh,Tunisia,Tunisia,0,1,0.00%
31,Egil Selvik,Norway,Norway,0,1,0.00%
32,Matt Turner,United States,United States,0,1,0.00%
33,Utkir Yusupov,Uzbekistan,Uzbekistan,0,1,0.00%
34,Jalal Hassan,Iraq,Iraq,0,1,0.00%
35,Edouard Mendy,Senegal,Senegal,0,2,0.00%
36,Jacob Widell Zetterstrom,Sweden,Sweden,0,2,0.00%
37,Aymen Dahmen,Tunisia,Tunisia,0,2,0.00%
38,Kristoffer Nordfeldt,Sweden,Sweden,0,2,0.00%
39,Abduvohid Nematov,Uzbekistan,Uzbekistan,0,2,0.00%
40,Ahmed Basil,Iraq,Iraq,0,2,0.00%
41,Fernando Muslera,Uruguay,Uruguay,0,3,0.00%
42,Orlando Mosquera,Panama,Panama,0,3,0.00%
43,Seung-Gyu Kim,South Korea,South Korea,0,3,0.00%
44,Matej Kovar,Czech Republic,Czech Republic,0,3,0.00%
45,Max Crocombe,New Zealand,New Zealand,0,3,0.00%
46,Luca Zidane,Algeria,Algeria,0,3,0.00%
47,Ugurcan Cakır,Turkey,Turkey,0,3,0.00%
48,Yazeed Abulaila,Jordan,Jordan,0,3,0.00%
49,Johny Placide,Haiti,Haiti,0,3,0.00%
50,Mahmud Abunada,Qatar,Qatar,0,3,0.00%
51,Lionel Mpasi,DR Congo (Zaire),Democratic Republic of Congo,0,4,0.00%
52,Alexander Schlager,Austria,Austria,0,4,0.00%
53,Manuel Neuer,Germany,Germany,0,4,0.00%
54,Bart Varbruggen,Netherlands,Netherlands,0,4,0.00%
55,Nikola Vasilj,Bosnia and Herzegovina,Bosnia and Herzegovina,0,4,0.00%
56,Orjan Nyland,Norway,Norway,0,5,0.00%
57,Mostafa Shobeir,Egypt,Egypt,0,5,0.00%

## Načini doseganja golov

In [27]:
goal_types = goal_types.replace("-", 0)
goal_types

,Clubs,Goals,Open Play,Cross,Free Kick,Direct Free Kick,Throw In,Penalty,Corner,Other
0,France,20,17,1,0,0,0,1,1,0
1,England,20,9,4,0,0,0,3,4,0
2,Argentina,18,9,3,0,2,0,1,3,0
3,Spain,13,8,3,0,0,0,1,1,0
4,Belgium,13,6,5,0,0,0,1,1,0
5,Norway,12,9,2,0,0,0,0,1,0
6,Germany,11,7,2,0,0,0,1,1,0
7,Brazil,10,7,2,0,0,0,1,0,0
8,Morocco,10,7,1,1,0,0,0,1,0
9,Switzerland,10,7,1,0,0,0,2,0,0
10,Netherlands,10,4,4,1,0,0,0,1,0
11,Mexico,10,7,1,1,0,0,1,0,0
12,Senegal,10,9,0,0,0,0,0,1,0
13,United States,9,5,0,1,2,0,0,1,0
14,Canada,8,6,0,0,1,0,0,1,0
15,Egypt,8,4,1,1,0,0,0,2,0
16,Japan,8,6,1,0,0,0,0,1,0
17,Portugal,7,2,3,0,1,0,1,0,0
18,Sweden,7,6,0,1,0,0,0,0,0
19,Croatia,6,4,1,0,0,0,0,1,0
20,Colombia,5,3,2,0,0,0,0,0,0
21,Austria,5,4,0,0,0,0,1,0,0
22,DR Congo (Zaire),5,3,0,0,0,0,1,1,0
23,Ivory Coast,5,5,0,0,0,0,0,0,0
24,Algeria,5,3,0,0,0,0,0,2,0
25,Cape Verde,4,3,0,0,1,0,0,0,0
26,Bosnia and Herzegovina,4,1,0,0,0,0,0,3,0
27,New Zealand,4,2,0,0,0,0,0,2,0
28,Iran,3,2,1,0,0,0,0,0,0
29,Paraguay,3,1,0,1,0,0,0,1,0
30,Jordan,3,2,1,0,0,0,0,0,0
31,Uruguay,3,3,0,0,0,0,0,0,0
32,Turkey,3,3,0,0,0,0,0,0,0
33,Tunisia,2,0,1,0,0,0,0,1,0
34,Uzbekistan,2,2,0,0,0,0,0,0,0
35,Australia,2,2,0,0,0,0,0,0,0
36,South Africa,2,1,0,0,0,0,1,0,0
37,Ghana,2,1,0,1,0,0,0,0,0
38,South Korea,2,2,0,0,0,0,0,0,0
39,Ecuador,2,1,0,0,0,0,0,1,0
40,Czech Republic,2,1,0,0,0,1,0,0,0
41,Scotland,1,1,0,0,0,0,0,0,0
42,Curacao,1,1,0,0,0,0,0,0,0
43,Haiti,1,1,0,0,0,0,0,0,0
44,Iraq,1,0,1,0,0,0,0,0,0
45,Saudi Arabia,1,0,0,0,0,0,0,1,0
46,Qatar,1,1,0,0,0,0,0,0,0

Najprej poglejmo, katere reprezentance so na svetovnem prvenstvu zadele največ golov.

In [35]:
najvec_golov = goals_for.head(10)
najvec_golov

   Goals For          Clubs FH  SH F15 L10  Pld
0         20        England  9  11   2   5    8
1         20         France  5  15   2   4    8
2         19      Argentina  6  13   1  10    8
3         14          Spain  7   7   1   4    8
4         14        Belgium  4  10   1   6    6
5         13         Norway  6   7   0   3    6
6         11        Germany  4   7   2   2    4
7         11    Netherlands  4   7   3   1    4
8         11  United States  8   3   3   2    5
9         10        Senegal  2   8   1   3    4

Poglejmo, katere reprezentance so zadele vsaj 10 golov, in jih razvrstimo glede na število golov v prvem polčasu.

In [36]:
vsaj_10_golov = goals_for[goals_for["Goals For"] >= 10]
vsaj_10_golov.sort_values("FH", ascending=False)

    Goals For          Clubs FH  SH F15 L10  Pld
0          20        England  9  11   2   5    8
8          11  United States  8   3   3   2    5
3          14          Spain  7   7   1   4    8
2          19      Argentina  6  13   1  10    8
5          13         Norway  6   7   0   3    6
10         10         Brazil  6   4   1   2    5
1          20         France  5  15   2   4    8
4          14        Belgium  4  10   1   6    6
6          11        Germany  4   7   2   2    4
7          11    Netherlands  4   7   3   1    4
11         10         Mexico  4   6   1   1    5
13         10        Morocco  4   6   1   4    6
9          10        Senegal  2   8   1   3    4
12         10    Switzerland  2   8   1   3    6

Poglejmo še, katere reprezentance so zadele vsaj 10 golov, in jih razvrstimo po številu zadetih golov v zadnjih desetih minutah.

In [39]:
vsaj_10_golov["L10"] = vsaj_10_golov["L10"].astype(int)
vsaj_10_golov.sort_values("L10", ascending=False)

    Goals For          Clubs FH  SH F15  L10  Pld
2          19      Argentina  6  13   1   10    8
4          14        Belgium  4  10   1    6    6
0          20        England  9  11   2    5    8
1          20         France  5  15   2    4    8
3          14          Spain  7   7   1    4    8
13         10        Morocco  4   6   1    4    6
5          13         Norway  6   7   0    3    6
9          10        Senegal  2   8   1    3    4
12         10    Switzerland  2   8   1    3    6
6          11        Germany  4   7   2    2    4
8          11  United States  8   3   3    2    5
10         10         Brazil  6   4   1    2    5
7          11    Netherlands  4   7   3    1    4
11         10         Mexico  4   6   1    1    5